package middleware

const (
	MLEARNING_CONTEXT = "MLEARNING_CONTEXT"
	MLEARNING_RESPONSE = "MLEARNING_RESPONSE"
	MLEARNING__EMAIL = "MLEARNING__EMAIL"
	MIDDLEWARE_FILE_SYSTEM = "MIDDLEWARE_FILE_SYSTEM"
	MLEARNING_HEADER_AUTHORIZATION = "Authorization"
)
