package middleware
import "errors"

const (
	MLEARNING_CONTENT = "MLEARNING_CONTENT"
	MLEARNING_RESPONSE = "MLEARNING_RESPONSE"
	MLEARNING__EMAIL = "MLEARNING__EMAIL"
	MIDDLEWARE_TOKEN = "TOKEN_TEST"
	MIDDLEWARE_FILE_SYSTEM = "MIDDLEWARE_FILE_SYSTEM"
	MLEARNING_HEADER_AUTHORIZATION = "Authorization"
)
var (
	NO_AUTHORITATION_ERR = errors.New("登录失效,请重新登录")
)