package service

const (
	SERVICE_TOKEN_INSERT_ERR = "SERVICE_TOKEN_INSERT_ERR"
	SERVICE_TOKEN_COUNT_ERR = "SERVICE_TOKEN_COUNT_ERR"
	SERVICE_COURSE_MARK_ERR = "SERVICE_COURSE_MARK_ERR"
	SERVICE_COURSE_MARK_CANCEL_ERR = "SERVICE_COURSE_MARK_CANCEL_ERR"
	SERVICE_COURSE_LOAD_ERR = "SERVICE_COURSE_LOAD_ERR"
	SERVICE_COURSE_FLUSH_ERR = "SERVICE_COURSE_FLUSH_ERR"
	SERVICE_COURSE_UPDATE_ERR = "SERVICE_COURSE_UPDATE_ERR"

	SERVICE_FILE_ADD_ERR = "SERVICE_FILE_ADD_ERR"
	SERVICE_FILE_UPDATE_ERR = "SERVICE_FILE_UPDATE_ERR"
	SERVICE_FILE_DELETE_ERR = "SERVICE_FILE_DELETE_ERR"
)
